Development/Cheers_Mani_hec_changes_14_may/EWC_NSAA/Models/HECActivity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EWC_NSAA.Models
{
    public class HECActivity
    {
        public string ReasonForCancellation { get; set; }
    }
}

Development/Cheers_Mani_hec_changes_14_may/EWC_NSAA/ViewModels/HECDetails.cs
using EWC_NSAA.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EWC_NSAA.Models
{
    public class HECDetails
    {
        public string HECIncidentNumber { get; set; }
        public DateTime HECIncidentDateStamp { get; set; }
        [Display(Name ="Date")]
        public DateTime HECActivityDate { get; set; }
        [Display(Name = "Activity Type")]
        public int HECActivityType { get; set; }
        [Display(Name = "Activity Type")]
        public string OtherActivityType { get; set; }
        [Display(Name = "Activity Cancelled")]
        public bool HECActivityCancelled { get; set; } = false;
        [Display(Name = "Reason for Cancellation")]
        public string HECactivityCancellationReason { get; set; }
        [Display(Name = "Name")]
        public string HECNameOrPurpose { get; set; }
        [Display(Name = "Type of Activity")]
        public int HECTypeOfActivity { get; set; }
        [Display(Name = "Collaborator")]
        public int HECCollaborator { get; set; }
        [Display(Name = "Contribution")]
        public int HECCollaboratorContribution { get; set; }
        public string OtherCollaboratorContribution { get; set; }
        public string HECActivityAddress1 { get; set; }
        public string HECActivityAddress2 { get; set; }
        [Display(Name = "City")]
        public string HECActivityCity { get; set; }
        [Display(Name = "Zip")]
        public string HECActivityZip { get; set; }
        [Display(Name = "CHW")]
        public int HECCHW { get; set; }
        [Display(Name = "Other Attendee")]
        public string HECOtherAttendees { get; set; }
        [Display(Name = "Population")]
        public int HECPopulation { get; set; }
        [Display(Name = "Language")]
        public int HECLanguage { get; set; }
        [Display(Name = "Discussed")]
        public int HECDiscussed { get; set; }
        [Display(Name = "Other Discussed")]
        public string OtherDiscussed { get; set; }
        [Display(Name = "Test")]
        public int HECPrePostTest { get; set; }
        [Display(Name = "Result")]
        public int HECResult { get; set; }
        [Display(Name = "Other Result")]
        public string OtherResult { get; set; }

        [Display(Name = "My Role")]
        public int HECMyRole { get; set; }
        [Display(Name = "Other My Role")]
        public string OtherMyRole { get; set; }
        [Display(Name = "Confirm Attendance")]
        public bool HECConfirmAttendance { get; set; }
        [Display(Name = "Travel")]
        public bool HECActivityTravel { get; set; }
        [Display(Name = "Notes")]
        public string HECActivityNotes { get; set; }
    }
}

Development/Cheers_Mani_hec_changes_14_may/EWC_NSAA/ViewModels/HECViewModel.cs
using EWC_NSAA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EWC_NSAA.ViewModels
{
    public class HECViewModel
    {
        public HECActivity HECActivity { get; set; }
        public HECDetails HECDetails { get; set; }
        public HECCommunityEvents HECCommunityEvents { get; set; }
        public HECParticipant HECParticipant { get; set; }
       

    }
}

Development/Cheers_Mani_hec_changes_14_may/EWC_NSAA/Controllers/HECActivitiesController.cs
using EWC_NSAA.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EWC_NSAA.Controllers
{
    public class HECActivitiesController : Controller
    {
        // GET: HECActivities
        public ActionResult Index()
        {
            var model = new HECViewModel();
            model.HECActivity = new Models.HECActivity();
            model.HECDetails = new Models.HECDetails();
            model.HECCommunityEvents = new Models.HECCommunityEvents();
            model.HECParticipant = new Models.HECParticipant();
            return View(model);
        }

        // GET: HECActivities/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HECActivities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HECActivities/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: HECActivities/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HECActivities/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: HECActivities/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HECActivities/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Development/Cheers_Mani_hec_changes_14_may/EWC_NSAA/Views/HECActivities/HECActivity.cshtml
@model EWC_NSAA.Models.HECActivity

<div class="panel-body" style="min-height: 550px; max-height: 550px; ">
    <div class="row">
        <div class="col-lg-9">
        </div>
        <div class="col-lg-3 alignright">
            <h4> <b> Incident #:</b>12345</h4>
            <h4> <b> Date:</b> 05/05/2018</h4>
        </div>
    </div>
    <div class="row">

        <div class="col-md-3">
            <h4> <b> Date of Activity</b> </h4>
            <div class="input-group date">
                <div class="input-group-addon">
                    <i class="fa fa-calendar"></i>
                </div>
                <text class="form-control" placeholder="" required></text>
            </div>
        </div>
        </div> <br />
        <div class="row">

            <div class="col-lg-3">
                <div class="form-group">

                    <input type="checkbox" name="preferenceday3" id="hecClass" autocomplete="off" checked="">
                    <span class="content">HE Class</span>

                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">

                    <input type="checkbox" name="preferenceday3" id="outreach" autocomplete="off">
                    <span class="content">1:1 Outreach</span>

                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">

                    <input type="checkbox" name="preferenceday3" id="community" autocomplete="off">
                    <span class="content">Community Events</span>

                </div>
            </div>

                


            </div><br />
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">

                <input type="checkbox" name="preferenceday3" id="preferenceday3" autocomplete="off">
                <span class="content">Activity Cancelled</span>
                <h4> <b> Reason For Cancellation</b> </h4>
                @*@Html.TextAreaFor(m => m.ReasonForCancellation)*@
                <textarea class="form-control" rows="3" placeholder="" required></textarea>
            </div>
        </div>
    </div>
    </div>

<div class="content" >
    <div class="form-group" style="width:100%; ">

        <div class="pull-right" >
            <a href="#" class="btn btn-success" style="min-width: 120px; max-width: 120px;   background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;" id="activate-step"><span class="glyphicon glyphicon-floppy-save"></span>  &nbsp;Save</a>
            <a onclick="" class="btn" id="back-step" style="min-width: 120px; max-width: 120px;   cursor:pointer;background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;color: #fff;"> <span class="glyphicon glyphicon-arrow-right"></span>  &nbsp;Next </a>



        </div>
    </div>
</div>

Development/Cheers_Mani_hec_changes_14_may/EWC_NSAA/Views/HECActivities/HECCommunityEvents.cshtml
@model EWC_NSAA.Models.HECCommunityEvents

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="panel-body" style="min-height: 550px; max-height: 550px; ">
        <div class="row">
            <div class="col-lg-9">
                <div class="form-group">

                    <h4> <b> Business Name</b> </h4>

                    @Html.EditorFor(model => model.HECCommunityBusinessName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Business Name" } })
                    @Html.ValidationMessageFor(model => model.HECCommunityBusinessName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-lg-3">
                <div class="form-group">

                    <h4> <b>NPI #</b> </h4>

                    @Html.EditorFor(model => model.HECCommunityNPI, new { htmlAttributes = new { @class = "form-control", @placeholder = "NPI" } })
                    @Html.ValidationMessageFor(model => model.HECCommunityNPI, "", new { @class = "text-danger" })
                </div>

            </div>

        </div>

        <div class="row">
            <div class="col-lg-4">
                <div class="form-group">

                    <h4> <b> Provider’s Name</b> </h4>
                    @Html.EditorFor(model => model.HECCommunityProviderFirstName, new { htmlAttributes = new { @class = "form-control", @placeholder = "First name" } })
                    @Html.ValidationMessageFor(model => model.HECCommunityProviderFirstName, "", new { @class = "text-danger" })

                </div>

            </div>
            <div class="col-lg-4">
                <div class="form-group">
                    <h4> <b>   &nbsp;</b> </h4>
                    @Html.EditorFor(model => model.HECCommunityProviderLastName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Last Name" } })
                    @Html.ValidationMessageFor(model => model.HECCommunityProviderLastName, "", new { @class = "text-danger" })
                </div>

            </div>

            <div class="col-lg-4">
                <div class="form-group">

                </div>

            </div>
            <div class="col-lg-2">
                <div class="form-group">

                </div>

            </div>

        </div>

        <div class="row">
            <div class="col-lg-6">
                <div class="form-group">

                    <h4> <b> EWC Provider?</b> </h4>
                    <div class="form-group form-inline">
                        <div class="form-group">

                            <input type="checkbox" name="preferenceday3" id="preferenceday3" autocomplete="off">
                            <span class="content">Yes</span>

                        </div> &nbsp; &nbsp; &nbsp;
                        <div class="form-group">

                            <input type="checkbox" name="preferenceday3" id="preferenceday3" autocomplete="off">
                            <span class="content">No</span>

                        </div>&nbsp; &nbsp; &nbsp;
                        <div class="form-group">

                            <input type="checkbox" name="preferenceday3" id="preferenceday3" autocomplete="off">
                            <span class="content">Unknown</span>

                        </div>
                    </div>


                </div>

            </div>

            <div class="col-lg-2">
                <div class="form-group">

                </div>

            </div>

        </div>

    </div>

    <div class="content">
        <div class="form-group" style="width:100%">


            <div class="row pull-right">

                <a onclick="showMore('screen1')" class="btn hide previousButton" style="min-width: 120px; max-width: 120px; cursor:pointer;background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;color: #fff;"> <span class="glyphicon glyphicon-arrow-left"></span>  &nbsp;Previous   </a>
                <a href="#" class="btn btn-success" style="min-width: 120px; max-width: 120px;   background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;" id="activate-step"><span class="glyphicon glyphicon-floppy-save"></span>  &nbsp;Save</a>

                <a onclick="showMore('screen2')" class="btn nextButton" style="min-width: 120px; max-width: 120px; cursor:pointer;background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;color: #fff;"> &nbsp;&nbsp;<span class="glyphicon glyphicon-arrow-right"></span>&nbsp;Next  </a>
                &nbsp;
            </div>

        </div>
    </div>
}

Development/Cheers_Mani_hec_changes_14_may/EWC_NSAA/Views/HECActivities/Index.cshtml
@model EWC_NSAA.ViewModels.HECViewModel


<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row col-md-12">
        <!-- widget content -->
        <div class="widget-body margin24">
            <div class="row">
                <form id="wizard-1" novalidate="novalidate">
                    <div id="bootstrap-wizard-1" class="col-sm-12">
                        <div class="form-bootstrapWizard col-lg-11 col-lg-offset-4 text-center">
                            <ul class="bootstrapWizard form-wizard">
                                <li class="active" data-target="#step1">
                                    <a onclick="return showHideTab('one')" data-toggle="tab" class="active" style="cursor:pointer"> <span class="step">1</span> <span class="title">Activity</span> </a>
                                </li>
                                <li data-target="#step2" class="">
                                    <a onclick="return showHideTab('two','two')" data-toggle="tab" style="cursor:pointer"> <span class="step">2</span> <span class="title">Details</span> </a>
                                </li>
                                <li data-target="#step3" class="">
                                    <a onclick="return showHideTab('three','three')" data-toggle="tab" style="cursor:pointer"> <span class="step">3</span> <span class="title hecParticipant">Participant Info</span><span class="title hecCommunity">Community Event</span> </a>
                                </li>

                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <br />
                        <div class="tab-content" style="margin-top:-90px">
                            <div class="panel panel-default margin30" id="tab1">
                                <div class="panel-body  col-md-12" style="border: none; margin-bottom: -15px;">

                                    <div class="tab-pane active">
                                        @Html.Partial("HECActivity", Model.HECActivity)
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default margin30" id="tab2">
                                <div class="panel-body  col-md-12" style="border: none; margin-bottom: -15px;">
                                    <div class="tab-pane hecDetails">
                                        @Html.Partial("HECDetails", Model.HECDetails)
                                    </div>
                                </div>
                            </div>
                            <div class="panel panel-default margin30" id="tab3">
                                <div class="panel-body  col-md-12">
                                    <div class="tab-pane hecCommunity">
                                        @Html.Partial("HECCommunityEvents", Model.HECCommunityEvents)
                                    </div>
                                    <div class="tab-pane hecParticipant">
                                        @Html.Partial("HECParticipant", Model.HECParticipant)
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </form>
            </div>
        </div>
        @*<div class="content">
            <div class="form-group" style="width:100%">

                <div class="pull-right">
                    <a href="#" class="btn btn-success" style="min-width: 120px; max-width: 120px;   background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;" id="activate-step"><span class="glyphicon glyphicon-floppy-save"></span>  &nbsp;Save</a>
                    <a onclick="" class="btn" id="back-step" style="min-width: 120px; max-width: 120px;   cursor:pointer;background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;color: #fff;"> <span class="glyphicon glyphicon-arrow-right"></span>  &nbsp;Next </a>
                   


                </div>
            </div>
        </div>*@
        <br />
        <br />
        <!-- end widget content
           </div>
        -->
        <!-- end widget div -->
    </div>

    
}
<script type="text/javascript">
    $(document).ready(function () {
        $('.hecClass').addClass('hide');
        $('.hecCommunity').addClass('hide');
    })
    $(document).on('click', '.panel-heading span.clickable', function (e) {
        var $this = $(this);
        if (!$this.hasClass('panel-collapsed')) {
            $this.parents('.panel').find('.panel-body').slideUp();
            $this.addClass('panel-collapsed');
            $this.find('i').removeClass('glyphicossn-chevron-up').addClass('glyphicon-chevron-down');
        } else {
            $this.parents('.panel').find('.panel-body').slideDown();
            $this.removeClass('panel-collapsed');
            $this.find('i').removeClass('glyphicon-chevron-down').addClass('glyphicon-chevron-up');
        }

    });
    $(':checkbox').change(function (e) {
        if (e.originalEvent.path[0].id == 'hecClass' && this.checked) {
            $('.hecClass').addClass('hide');
            $('.hecCommunity').addClass('hide');
            $('.hecParticipant').removeClass('hide');
        }
        else {
            $('.hecClass').removeClass('hide');
        }
        if (e.originalEvent.path[0].id == 'outreach' && this.checked) {
            $('.hecCommunity').addClass('hide');
            $('.hecParticipant').removeClass('hide');
            $('.outreach').addClass('hide');
        }
        else {
            $('.outreach').removeClass('hide');
        }
        if (e.originalEvent.path[0].id == 'community' && this.checked) {
            $('.hecCommunity').removeClass('hide');
            $('.hecParticipant').addClass('hide');
            $('.community').addClass('hide');
        }
        else {
            $('.community').removeClass('hide');
        }
    });


    $(document).ready(function () {
        $('#tab2').css('display', 'none');
        $('#tab3').css('display', 'none');

    })

    function showHideTab(currentTab, previous) {
        
        if (validateForm(currentTab, previous)) {
            if (currentTab == "one") {
                $('#tab1').css('display', 'block');
                $('#tab2').css('display', 'none');
                $('#tab3').css('display', 'none');
            }
            else if (currentTab == "two") {
                $('#tab1').css('display', 'none');
                $('#tab2').css('display', 'block');
                $('#tab3').css('display', 'none');
            }
            else if (currentTab == "three") {
                $('#tab1').css('display', 'none');
                $('#tab2').css('display', 'none');
                $('#tab3').css('display', 'block');
            }
        }

    }

    function validateForm(currText, previous) {
        var tabVal = "";
        if (previous != undefined) {
            currText = previous;
        }
        if (currText == "one") {
            tabVal = "#step1";
        }
        else if (currText == "two") {

            tabVal = "#step2";
        }
        else if (currText == "three") {
            tabVal = "#step3";
        }


        return true;
    }
</script>

Development/Cheers_Mani_hec_changes_14_may/EWC_NSAA/Views/Home/HECDashboard.cshtml
<div class="row col-lg-12 panel-heading" style="min-height:60px;  border-color:rgb(221, 221, 221); color: #060606;box-shadow: 0px 2px 5px 0 rgba(0, 5, 0, 0.1) , 0px 2px 10px 0 rgba(0, 0, 0, 0.2); MARGIN-LEFT:0px; margin-top: 20px; align-content:center">
    <div class="col-lg-6" style="margin-right: 60px; ">
        <h4> <b>  &nbsp;</b> </h4>
    </div>
    <div class="col-lg-1" style="margin-top: 6px; margin-right: 4px;">
        <h4> <b>  SEARCH</b> </h4>
    </div>
    <div class="col-lg-1" style="margin-top: 12px; margin-right: 14px;">
        <div class="form-group">
            <label class="checkbox-inline"><input type="checkbox" value="">&nbsp;&nbsp;Activity</label>
        </div>

    </div>
    
    <div class="col-lg-2" style="margin-top: 12px; ">
        <div class="form-group">

            <label class="checkbox-inline"><input type="checkbox" value="">&nbsp;&nbsp;Collaborator</label>

        </div>

    </div>

    <div class="col-lg-1" style="margin-top: 6px; ">
        <div class="form-group">

            <a href="#" class="btn" style=" cursor:pointer;background-color: #3a3a3a;border: 2px #cfcfcf;font-size: 18px !important;color: #fff;" id="activate-step"> <span class="glyphicon glyphicon-search"></span>  </a>

        </div>

    </div>
</div>
<div class="row col-md-12" style="min-height: 700px; max-height: 700px; MARGIN-LEFT:0px;margin-top: 40px;">



    <div class="col-lg-6 col-md-6">
        <div class="panel panel-primary" style="border-color:rgb(221, 221, 221); color: #060606;box-shadow: 0px 2px 5px 0 rgba(0, 0, 0, 0.1), 0px 2px 10px 0 rgba(0, 0, 0, 0.2);">
            <div class="panel-heading" style="background-color: rgb(139, 174, 36);border-color:rgb(139, 174, 36);">
                <div class="row">

                    <div class="col-md-12">

                        <div class="text-center">HEC</div>
                    </div>
                </div>
            </div>
           
            <a style="color: #060606;" href="@Url.Action("Index", "HECActivities")">
                <div class="panel-footer">
                    <span class="pull-left">HEC Activities</span>
                    <div class="clearfix"></div>
                </div>
            </a>

            <a href="@Url.Action("Index2", "Enrollment")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer">
                    <span class="pull-left">CHW Recruitment & Training</span>
                    <div class="clearfix"></div>
                </div>
            </a>
            <a href="@Url.Action("PartnersCollaboratorList", "PartnersCollaborators")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer">
                    <span class="pull-left">Reports</span>
                    <div class="clearfix"></div>
                </div>
            </a>

        </div>
        <br />
    </div>
    <div class="col-md-6">

        <div class="panel panel-primary" style="border-color:rgb(221, 221, 221); color: #060606;box-shadow: 0px 2px 5px 0 rgba(0, 0, 0, 0.1), 0px 2px 10px 0 rgba(0, 0, 0, 0.2);">
            <div class="panel-heading" style="background-color:  rgb(105, 105, 103);border-color:rgb(105, 105, 103);">
                <div class="row">

                    <div class="col-md-12">

                        <div class="text-center">Search</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("SearchActivity", "Home")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer" style="background-color:  orange; ">
                    <b>  Activity</b>

                </div>
            </a>

            <a href="@Url.Action("PartnersCollaboratorList", "PartnersCollaborators")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer" style="background-color:  cornflowerblue; ">
                    <b>  Collaborator</b>

                </div>
            </a>
            <a href="@Url.Action("SearchProvider", "Home")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer" style="background-color:  green; ">
                    <b>  Provider</b>

                </div>
            </a>



        </div>
    </div>

    <div class="col-md-6">

        
    
        <div class="panel panel-primary" style="border-color:rgb(221, 221, 221); color: #060606;box-shadow: 0px 2px 5px 0 rgba(0, 0, 0, 0.1), 0px 2px 10px 0 rgba(0, 0, 0, 0.2);">
            <div class="panel-heading" style="background-color:  rgb(105, 105, 103);border-color:rgb(105, 105, 103);">
                <div class="row">

                    <div class="col-md-12">

                        <div class="text-center">Instant Messaging &nbsp; 
                            <a href="@Url.Action("Inbox", "InstantMessage")" onclick="navigationClick()" style="color: #060606;">
                                <span class="glyphicon glyphicon-envelope"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

           


            <a href="@Url.Action("Inbox", "InstantMessage")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer">
                    <span class="pull-left">Message 1</span>
                    <div class="clearfix"></div>
                </div>
            </a>

            <a href="@Url.Action("Index2", "Enrollment")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer">
                    <span class="pull-left">Message 2</span>
                    <div class="clearfix"></div>
                </div>
            </a>
            <a href="@Url.Action("PartnersCollaboratorList", "PartnersCollaborators")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer">
                    <span class="pull-left">Message 3</span>
                    <div class="clearfix"></div>
                </div>
            </a>

        </div>
    </div> 
    <br />


</div><br />