Development/Cheers_07_May_2018/Cheers_Live/EWC_NSAA/EWC_NSAA/Controllers/PCPEnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EWC_NSAA.Controllers
{
    public class PCPEnrollmentController : Controller
    {
        // GET: PCPEnrollment
        public ActionResult Index()
        {
            return View();
        }
        // GET: Pre Enrollment
        public ActionResult PreEnrollment()
        {
            return View();
        }
        // GET: Enrollment
        public ActionResult Enrollment()
        {
            return View();
        }
        // GET: Management
        public ActionResult Management()
        {
            return View();
        }
    }
}

Development/Cheers_07_May_2018/Cheers_Live/EWC_NSAA/EWC_NSAA/Controllers/PartnersCollaboratorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EWC_NSAA.Controllers
{
    public class PartnersCollaboratorsController : Controller
    {
        // GET: PartnersCollaborators
        public ActionResult PartnersCollaboratorList()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult _PartnersSearch()
        {
            return PartialView();
        }

        public ActionResult _List()
        {
            return PartialView();
        }

        public ActionResult _Edit(int id)
        {
            return PartialView();
        }

        public ActionResult _Deactivate(int id)
        {
            return PartialView();
        }

        public static List<SelectListItem> GetCityDropDown()
        {
            List<SelectListItem> cityList = new List<SelectListItem>();
            cityList.Add(new SelectListItem { Text = "Houston", Value = "1" });
            cityList.Add(new SelectListItem { Text = "Texas", Value = "2" });
            cityList.Add(new SelectListItem { Text = "Newyork", Value = "3" });
            cityList.Add(new SelectListItem { Text = "California", Value = "4" });
            return cityList;
        }

        public static List<SelectListItem> GetServiceDropDown()
        {
            List<SelectListItem> cityList = new List<SelectListItem>();
            cityList.Add(new SelectListItem { Text = "Service Type 1", Value = "1" });
            cityList.Add(new SelectListItem { Text = "Service Type 2", Value = "2" });
            cityList.Add(new SelectListItem { Text = "Service Type 3", Value = "3" });
            cityList.Add(new SelectListItem { Text = "Service Type 4", Value = "4" });
            return cityList;
        }

        public static List<SelectListItem> GetCountyDropDown()
        {
            List<SelectListItem> cityList = new List<SelectListItem>();
            cityList.Add(new SelectListItem { Text = "Morris", Value = "1" });
            cityList.Add(new SelectListItem { Text = "Brooklyn", Value = "2" });
            cityList.Add(new SelectListItem { Text = "Los Angeles", Value = "3" });
            cityList.Add(new SelectListItem { Text = "Fairfax", Value = "4" });
            return cityList;
        }

        public static List<SelectListItem> GetCategoryDropDown()
        {
            List<SelectListItem> cityList = new List<SelectListItem>();
            cityList.Add(new SelectListItem { Text = "Category 1", Value = "1" });
            cityList.Add(new SelectListItem { Text = "Category 2", Value = "2" });
            cityList.Add(new SelectListItem { Text = "Category 3", Value = "3" });
            cityList.Add(new SelectListItem { Text = "Category 4", Value = "4" });
            return cityList;
        }

        public static List<SelectListItem> GetPopulationDropDown()
        {
            List<SelectListItem> cityList = new List<SelectListItem>();
            cityList.Add(new SelectListItem { Text = "Population 1", Value = "1" });
            cityList.Add(new SelectListItem { Text = "Population 2", Value = "2" });
            cityList.Add(new SelectListItem { Text = "Population 3", Value = "3" });
            cityList.Add(new SelectListItem { Text = "Population 4", Value = "4" });
            return cityList;
        }
    }
}

Development/Cheers_07_May_2018/Cheers_Live/EWC_NSAA/EWC_NSAA/Views/Barriers/clinicalservices.cshtml
@{
    ViewBag.Title = "clinicalservices";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Enrollment";
}
@*<div class="panel-heading" style="background-color: rgb(203, 52, 60);border-color:rgb(203, 52, 60);">*@

<div class="row col-md-12" style="MARGIN-LEFT:0px;margin-top: 40px;">



    <div class="col-lg-6 col-md-6">
        <div class="panel panel-primary" style="border-color:rgb(221, 221, 221); color: #060606;box-shadow: 0px 2px 5px 0 rgba(0, 0, 0, 0.1), 0px 2px 10px 0 rgba(0, 0, 0, 0.2);">
            <div class="panel-heading" style="background-color: rgb(203, 52, 60);border-color:rgb(203, 52, 60);">
                <div class="row">

                    <div class="col-md-12">

                        <div class="text-center">Provider Enrollment & Management</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("PreEnrollment", "PCPEnrollment")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer">
                    <span class="pull-left">Pre-Enrollment</span>
                    <div class="clearfix">
                       
                    </div>
                </div>
            </a>

            <a href="@Url.Action("Enrollment", "PCPEnrollment")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer">
                    <span class="pull-left">Enrollment</span>
                    <div class="clearfix">
                     
                    </div>
                </div>
            </a>
            <a href="@Url.Action("Management", "PCPEnrollment")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer">
                    <span class="pull-left">Management</span>
                    <div class="clearfix">
                   
                    </div>
                </div>
            </a>

        </div>
        <div class="panel panel-primary" style="border-color:rgb(221, 221, 221); color: #060606;box-shadow: 0px 2px 5px 0 rgba(0, 0, 0, 0.1), 0px 2px 10px 0 rgba(0, 0, 0, 0.2);">
            <div class="panel-heading" style="background-color: rgb(203, 52, 60);border-color:rgb(203, 52, 60);">
                <div class="row">

                    <div class="col-md-12">

                        <div class="text-center">Clinical Services Activities</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Create", "Enrollment")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer">
                    <span class="pull-left">Reports</span>
                    <div class="clearfix"></div>
                </div>
            </a>

            <a href="@Url.Action("Index2", "Enrollment")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer">
                    <span class="pull-left">Mandated Attendance</span>
                    <div class="clearfix"></div>
                </div>
            </a>
            

        </div>
        <br />
    </div>

    <div class="col-md-6">

        
        <div class="panel panel-primary" style="border-color:rgb(221, 221, 221); color: #060606;box-shadow: 0px 2px 5px 0 rgba(0, 0, 0, 0.1), 0px 2px 10px 0 rgba(0, 0, 0, 0.2);">
            <div class="panel-heading" style="background-color:  rgb(105, 105, 103);border-color:rgb(105, 105, 103);">
                <div class="row">

                    <div class="col-md-12">

                        <div class="text-center">Instant Messaging</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Create", "Enrollment")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer">
                    <span class="pull-left">Message 1</span>
                    <div class="clearfix"></div>
                </div>
            </a>

            <a href="@Url.Action("Index2", "Enrollment")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer">
                    <span class="pull-left">Message 2</span>
                    <div class="clearfix"></div>
                </div>
            </a>
            <a href="@Url.Action("PartnersCollaboratorList", "PartnersCollaborators")" onclick="navigationClick()" style="color: #060606;">
                <div class="panel-footer">
                    <span class="pull-left">Message 3</span>
                    <div class="clearfix"></div>
                </div>
            </a>

        </div>
    </div>
    <br />


</div>